### ISSUE TITLE
Q33. Answer Correction (GitOps at Scale - Level 2)

### ISSUE THREAD

**Issue by daniloopinheiro** [rakshixh-me/Codefresh-GitOps-for-ArgoCD-Certification#5]
Q33. Resource A is in the PreSync phase and Sync wave 10. Resource B is in the Sync phase and has Sync wave 20. Resource C is in the SyncFail phase with sync wave 30

Wrong Answer : 
A will be deployed first, then B and then C

**Comment by rakshixh** [comment]
Thank you @daniloopinheiro 
I have made suggested changes to the Git Ops at Scale - Level 2, Question Number 33.

Happy Coding ✨

**Comment by rakshixh** [comment]
Thank you @daniloopinheiro 
I have made suggested changes to the Git Ops at Scale - Level 2, Question Number 33.

Happy Coding ✨
